**Artificial/Deep Neural Network**

In [2]:
import numpy as np 
import pandas as pd
import tensorflow as tf
tf.__version__

'2.12.0'

In [3]:
dataset = pd.read_csv('/content/Churn_Modelling.csv')
dataset.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
# split the data into dependent and independent variable
x = dataset.iloc[:,3:-1]
y = dataset.iloc[:,-1]

In [5]:
x.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10

In [18]:
x.shape

(10000, 11)

In [6]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [8]:
x = pd.get_dummies(x, columns=['Geography', 'Gender'])
x

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,1,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,1,0
3,699,39,1,0.00,2,0,0,93826.63,1,0,0,1,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,1,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,1,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,0,0,1,0
9998,772,42,3,75075.31,2,1,0,92888.52,0,1,0,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,1,0,0,1,0

In [9]:
x = x.drop(['Geography_France','Gender_Female'], axis = 1)

In [11]:
x.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,1,0

In [14]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_stand = sc.fit_transform(x)
x_stand

array([[-0.32622142,  0.29351742, -1.04175968, ..., -0.57873591,
        -0.57380915, -1.09598752],
       [-0.44003595,  0.19816383, -1.38753759, ..., -0.57873591,
         1.74273971, -1.09598752],
       [-1.53679418,  0.29351742,  1.03290776, ..., -0.57873591,
        -0.57380915, -1.09598752],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -0.57873591,
        -0.57380915, -1.09598752],
       [ 1.25683526,  0.29351742, -0.69598177, ...,  1.72790383,
        -0.57380915,  0.91241915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -0.57873591,
        -0.57380915, -1.09598752]])

In [16]:
# split the data into training and testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_stand, y, test_size=0.2, random_state=1)

# Building Deep Neural Network (MultiLayerPerceptron)

In [17]:
from tensorflow import keras

In [19]:
# creat APT
dnn = tf.keras.models.Sequential()
#Adding first Hidden Layer
dnn.add(tf.keras.layers.Dense(units=6, activation='relu'))           # in 1st hidden layer i am giving 6 neuron

#Adding second Hidden Layer
dnn.add(tf.keras.layers.Dense(units=6, activation='relu'))           # units should be equal or less than hidden layer 1

# Tensorflow is a backend language, keras is a frontend language, layers means hidden layer
# Dense means fully connected ie., each input data is individually connected to each layers/neuron and we are using relu as a activation functions

# adding output
dnn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))         # if it is binary class classification we can use sigmoid, if it is multiclass classification can use softMax because it gives multipule probability values

# Train the model
dnn.compile(optimizer='adam', loss = 'binary_crossentropy', metrics = ['accuracy'])   # since it is a binary classification we use binary crossentropy and we evaluate using accuracy mostly

# apply training dataset and fit the model
dnn.fit(x_train, y_train, batch_size = 32, epochs=100)

Epoch 1/100
250/250 [==============================] - 7s 3ms/step - loss: 0.5558 - accuracy: 0.7940
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4713 - accuracy: 0.7972
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4316 - accuracy: 0.8048
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4160 - accuracy: 0.8215
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4083 - accuracy: 0.8223
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4023 - accuracy: 0.8248
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3976 - accuracy: 0.8241
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3934 - accuracy: 0.8278
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3892 - accuracy: 0.8278
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3856 - accuracy: 0.8275
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3819 - accuracy: 0.8285
Epoch 12/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3792 - accuracy: 0.8328
Epoch 13/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3758 - accuracy: 0.8381
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3726 - accuracy: 0.8404
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3697 - accuracy: 0.8421
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3669 - accuracy: 0.8440
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3645 - accuracy: 0.8461
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3626 - accuracy: 0.8462
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3601 - accuracy: 0.8490
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3582 - accuracy: 0.8472
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3567 - accuracy: 0.8499
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3556 - accuracy: 0.8519
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3535 - accuracy: 0.8537
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3527 - accuracy: 0.8525
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3510 - accuracy: 0.8530
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3497 - accuracy: 0.8535
Epoch 27/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3487 - accuracy: 0.8543
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3476 - accuracy: 0.8558
Epoch 29/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3463 - accuracy: 0.8556
Epoch 30/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3460 - accuracy: 0.8554
Epoch 31/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3450 - accuracy: 0.8572
Epoch 32/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3444 - accuracy: 0.8562
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3438 - accuracy: 0.8586
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3435 - accuracy: 0.8583
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3432 - accuracy: 0.8575
Epoch 36/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3426 - accuracy: 0.8585
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3426 - accuracy: 0.8575
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3420 - accuracy: 0.8583
Epoch 39/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3416 - accuracy: 0.8600
Epoch 40/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3414 - accuracy: 0.8572
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3407 - accuracy: 0.8596
Epoch 42/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3406 - accuracy: 0.8586
Epoch 43/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3409 - accuracy: 0.8599
Epoch 44/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3404 - accuracy: 0.8584
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3402 - accuracy: 0.8589
Epoch 46/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3400 - accuracy: 0.8591
Epoch 47/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3401 - accuracy: 0.8595
Epoch 48/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3396 - accuracy: 0.8594
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3395 - accuracy: 0.8595
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3382 - accuracy: 0.8602
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3396 - accuracy: 0.8585
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3396 - accuracy: 0.8579
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3389 - accuracy: 0.8590
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3387 - accuracy: 0.8590
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3382 - accuracy: 0.8580
Epoch 56/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3385 - accuracy: 0.8595
Epoch 57/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3384 - accuracy: 0.8587
Epoch 58/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3389 - accuracy: 0.8610
Epoch 59/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3383 - accuracy: 0.8599
Epoch 60/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3385 - accuracy: 0.8593
Epoch 61/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3384 - accuracy: 0.8595
Epoch 62/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3382 - accuracy: 0.8595
Epoch 63/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3382 - accuracy: 0.8602
Epoch 64/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3382 - accuracy: 0.8585
Epoch 65/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3382 - accuracy: 0.8597
Epoch 66/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3378 - accuracy: 0.8601
Epoch 67/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3375 - accuracy: 0.8605
Epoch 68/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3375 - accuracy: 0.8587
Epoch 69/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3377 - accuracy: 0.8596
Epoch 70/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3377 - accuracy: 0.8597
Epoch 71/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3373 - accuracy: 0.8608
Epoch 72/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3380 - accuracy: 0.8601
Epoch 73/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3375 - accuracy: 0.8596
Epoch 74/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3372 - accuracy: 0.8602
Epoch 75/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3373 - accuracy: 0.8585
Epoch 76/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3374 - accuracy: 0.8594
Epoch 77/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3368 - accuracy: 0.8600
Epoch 78/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3372 - accuracy: 0.8590
Epoch 79/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3367 - accuracy: 0.8601
Epoch 80/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3371 - accuracy: 0.8602
Epoch 81/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3371 - accuracy: 0.8594
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3368 - accuracy: 0.8608
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3367 - accuracy: 0.8599
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3364 - accuracy: 0.8595
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3369 - accuracy: 0.8596
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3364 - accuracy: 0.8614
Epoch 87/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3366 - accuracy: 0.8610
Epoch 88/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3364 - accuracy: 0.8597
Epoch 89/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3365 - accuracy: 0.8602
Epoch 90/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3362 - accuracy: 0.8612
Epoch 91/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3361 - accuracy: 0.8610
Epoch 92/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3361 - accuracy: 0.8602
Epoch 93/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3361 - accuracy: 0.8601
Epoch 94/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3364 - accuracy: 0.8601
Epoch 95/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3360 - accuracy: 0.8611
Epoch 96/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3361 - accuracy: 0.8591
Epoch 97/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3354 - accuracy: 0.8577
Epoch 98/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3357 - accuracy: 0.8608
Epoch 99/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3356 - accuracy: 0.8596
Epoch 100/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3352 - accuracy: 0.8614

In [20]:
dnn.fit(x_train, y_train, batch_size = 32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3360 - accuracy: 0.8597
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3358 - accuracy: 0.8606
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3358 - accuracy: 0.8593
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3357 - accuracy: 0.8605
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3353 - accuracy: 0.8615
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3359 - accuracy: 0.8608
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3352 - accuracy: 0.8605
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3348 - accuracy: 0.8590
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3354 - accuracy: 0.8600
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3353 - accuracy: 0.8611
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3350 - accuracy: 0.8601
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3347 - accuracy: 0.8595
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3348 - accuracy: 0.8599
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3354 - accuracy: 0.8612
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3349 - accuracy: 0.8619
Epoch 16/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3346 - accuracy: 0.8596
Epoch 17/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3351 - accuracy: 0.8605
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3346 - accuracy: 0.8605
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3348 - accuracy: 0.8587
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3347 - accuracy: 0.8600
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3351 - accuracy: 0.8601
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3346 - accuracy: 0.8618
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3345 - accuracy: 0.8605
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3344 - accuracy: 0.8614
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3343 - accuracy: 0.8614
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3345 - accuracy: 0.8616
Epoch 27/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3346 - accuracy: 0.8600
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3343 - accuracy: 0.8605
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3338 - accuracy: 0.8595
Epoch 30/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3335 - accuracy: 0.8616
Epoch 31/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3340 - accuracy: 0.8608
Epoch 32/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3339 - accuracy: 0.8587
Epoch 33/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3337 - accuracy: 0.8595
Epoch 34/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3340 - accuracy: 0.8604
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3339 - accuracy: 0.8604
Epoch 36/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3331 - accuracy: 0.8606
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3338 - accuracy: 0.8599
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3335 - accuracy: 0.8611
Epoch 39/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3332 - accuracy: 0.8606
Epoch 40/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3333 - accuracy: 0.8614
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3332 - accuracy: 0.8600
Epoch 42/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3339 - accuracy: 0.8610
Epoch 43/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3337 - accuracy: 0.8596
Epoch 44/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3332 - accuracy: 0.8614
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3333 - accuracy: 0.8614
Epoch 46/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3328 - accuracy: 0.8591
Epoch 47/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3331 - accuracy: 0.8605
Epoch 48/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3332 - accuracy: 0.8591
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3330 - accuracy: 0.8605
Epoch 50/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3330 - accuracy: 0.8608
Epoch 51/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3327 - accuracy: 0.8606
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3328 - accuracy: 0.8600
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3327 - accuracy: 0.8619
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3326 - accuracy: 0.8618
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3324 - accuracy: 0.8609
Epoch 56/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3324 - accuracy: 0.8619
Epoch 57/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3325 - accuracy: 0.8618
Epoch 58/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3326 - accuracy: 0.8611
Epoch 59/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3328 - accuracy: 0.8620
Epoch 60/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3312 - accuracy: 0.8621
Epoch 61/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3323 - accuracy: 0.8614
Epoch 62/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3320 - accuracy: 0.8609
Epoch 63/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3324 - accuracy: 0.8621
Epoch 64/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3315 - accuracy: 0.8637
Epoch 65/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3315 - accuracy: 0.8621
Epoch 66/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3313 - accuracy: 0.8619
Epoch 67/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3307 - accuracy: 0.8631
Epoch 68/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3304 - accuracy: 0.8640
Epoch 69/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3305 - accuracy: 0.8637
Epoch 70/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3308 - accuracy: 0.8627
Epoch 71/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3309 - accuracy: 0.8626
Epoch 72/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3299 - accuracy: 0.8640
Epoch 73/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3303 - accuracy: 0.8627
Epoch 74/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3303 - accuracy: 0.8630
Epoch 75/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3295 - accuracy: 0.8639
Epoch 76/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3297 - accuracy: 0.8611
Epoch 77/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3300 - accuracy: 0.8619
Epoch 78/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3292 - accuracy: 0.8630
Epoch 79/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3296 - accuracy: 0.8630
Epoch 80/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3296 - accuracy: 0.8615
Epoch 81/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3298 - accuracy: 0.8624
Epoch 82/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3293 - accuracy: 0.8625
Epoch 83/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3295 - accuracy: 0.8622
Epoch 84/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3299 - accuracy: 0.8620
Epoch 85/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3290 - accuracy: 0.8634
Epoch 86/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3290 - accuracy: 0.8627
Epoch 87/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3291 - accuracy: 0.8629
Epoch 88/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3293 - accuracy: 0.8619
Epoch 89/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3285 - accuracy: 0.8633
Epoch 90/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3289 - accuracy: 0.8634
Epoch 91/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3292 - accuracy: 0.8633
Epoch 92/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3282 - accuracy: 0.8622
Epoch 93/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3290 - accuracy: 0.8630
Epoch 94/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3286 - accuracy: 0.8629
Epoch 95/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3286 - accuracy: 0.8626
Epoch 96/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3282 - accuracy: 0.8625
Epoch 97/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3282 - accuracy: 0.8633
Epoch 98/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3287 - accuracy: 0.8624
Epoch 99/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3285 - accuracy: 0.8619
Epoch 100/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3293 - accuracy: 0.8620

In [21]:
# Predict the test result
y_pred = dnn.predict(x_test)

63/63 [==============================] - 0s 2ms/step

In [23]:
y_pred = (y_pred>0.5)

In [24]:
from sklearn.metrics import accuracy_score, classification_report

In [25]:
accuracy_score(y_test, y_pred)

0.864

In [27]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.95      0.92      1585
           1       0.74      0.53      0.62       415

    accuracy                           0.86      2000
   macro avg       0.81      0.74      0.77      2000
weighted avg       0.86      0.86      0.86      2000

In this employee churn modeling project, we developed a deep learning model to predict employee churn within an organization. The model achieved an accuracy of 86% on both the training and testing datasets, indicating a balanced and reliable performance. This means that the model has successfully learned the patterns and features that distinguish between employees who are likely to stay and those who are likely to leave the organization.

The high accuracy achieved by the model suggests its potential as a valuable tool for identifying employees at risk of churn. By proactively identifying such employees, organizations can take appropriate actions to mitigate churn, such as implementing retention strategies, providing additional support, or addressing any underlying concerns.

Overall, this employee churn classification model demonstrates the effectiveness of deep learning in predicting employee churn and provides valuable insights for organizations to make data-driven decisions in their employee retention efforts.